import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import NavbarComponent from './components/NavbarComponent'
import classNames from 'classnames'
import FooterComponent from './components/ui/FooterComponent'
import { Toaster } from 'sonner'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      >
      <body className={classNames(montserrat.className, 'bg-white dark:bg-dark-secondary ')}>
        <NavbarComponent />
        {children}
        <footer>
          <FooterComponent />
        </footer>
        <Toaster />
      </body>
    </html>
  )
}
